### ISSUE TITLE
Proposition to move Thomas Braibant & Damien Pous' contribution AAC tactics

### ISSUE THREAD

**Issue by fakusb** [coq-community/manifesto#10]
Move a project to coq-community

Project name: AAC Tactics

Initial author(s): Thomas Braibant & Damien Pous

Current URL: https://github.com/coq-contribs/aac-tactics

Kind: plugin

License: LGPL 3

Description: This plugin provides tactics for rewriting universally quantified
equations, modulo associativity and commutativity of some operators.

Status: formerly maintained in coq-contribs

Previous maintainer: Matej Kosik (?)

New maintainer: Fabian Kunze

**Comment by Zimmi48** [comment]
Thanks!
The repository has now been transferred: https://github.com/coq-community/aac-tactics

I'll try to submit a PR the next few days to setup CI.

**Comment by Zimmi48** [comment]
@fakusb You should probably add yourself to the "watchers" of the aac-tactics repository, otherwise you risk missing some incoming issues or pull requests.

**Comment by fakusb** [comment]
Yesy that seems very reasonable, thanks for the hint!

**Comment by ejgallego** [comment]
This seems solved right?
