### ISSUE TITLE
Proposal to move Buchberger to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#100]
**Project name:** Buchberger

**Initial author(s):** Laurent Théry and Henrik Persson   

**Current URL:** https://github.com/coq-contribs/buchberger

**Kind:** extractable program

**License:** LGPL-2.1-or-later

**Description:** A machine-checked implementation of Buchberger's algorithm

**Status:** Part of coq-contribs and maintained until Coq 8.10, but not currently compatible with 8.11

**New maintainer:** @palmskog 

We are looking to do research on Coq projects with extraction, and this is a classic algorithm and project (described in a [JAR article](https://link.springer.com/article/10.1023/A:1026518331905)). A more modern and succinct [formalization](https://github.com/thery/grobner) (by Théry) exists, but to my knowledge this development is not meant to be extracted. Probably the formalizations could be connected quite easily, to allow better reasoning about extracted code and more choice for applied work.

I already have a fork working for 8.11 that I plan to merge with upstream: https://github.com/palmskog/buchberger/tree/port-8.11

**Comment by Zimmi48** [comment]
cc @thery

**Comment by thery** [comment]
fine with me. Do I have to do something?

**Comment by palmskog** [comment]
@thery @Zimmi48 unless you have reservations, I can take care of all the administrative details of the move, such as moving the repo and so on (and then closing the issue).

**Comment by palmskog** [comment]
@thery one final question: the repo is ambiguous as to whether the code is licensed under "LGPL-2.1-only" or "LGPL-2.1-or-later". In the spirit of more flexible licensing terms, would you agree to interpreting it as "LGPL-2.1-or-later"?

**Comment by thery** [comment]
> @thery one final question: the repo is ambiguous as to whether the code is licensed under "LGPL-2.1-only" or "LGPL-2.1-or-later". In the spirit of more flexible licensing terms, would you agree to interpreting it as "LGPL-2.1-or-later"?

fine with me

**Comment by thery** [comment]
> @thery @Zimmi48 unless you have reservations, I can take care of all the administrative details of the move, such as moving the repo and so on (and then closing the issue).

Perfect, thanks!

**Comment by Zimmi48** [comment]
@palmskog Can you really do the transfer yourself since you are only a member and not an owner of coq-contribs?

**Comment by palmskog** [comment]
@Zimmi48 apparently I could: https://github.com/coq-community/buchberger

**Comment by Zimmi48** [comment]
OK, great to hear!
