### ISSUE TITLE
Proposal to move project coq-show to coq-community

### ISSUE THREAD

**Issue by liyishuai** [coq-community/manifesto#102]
**Project name:** coq-show

**Initial author(s):**
  - Leonidas Lampropoulos (@lemonidas)
  - Maxime Dénès (@maximedenes)
  - Cătălin Hrițcu (@catalin-hritcu)
  - Benjamin C. Pierce (@bcpierce00)

**Current URL:** https://github.com/liyishuai/coq-show

**Kind:** pure Coq library

**License:** BSD 3-Clause "New" or "Revised" License

**Description:** A clone of the Show class in Haskell.

**Status:** New repository, picked from https://github.com/QuickChick/QuickChick/blob/master/src/Show.v

**Motivation**:
- coq-community/coq-ext-lib#75
- QuickChick/QuickChick#168

**New maintainer:**
- @liyishuai

**Comment by Zimmi48** [comment]
Discussion on this proposal is currently happening at https://github.com/QuickChick/QuickChick/issues/168#issuecomment-634354957. It seems that there is some risk of redundancy between coq-show and coq-ceres.

**Comment by liyishuai** [comment]
After discussion with @Lysxia we agree that the current coq-show seems redundant given coq-ceres. Closing until notable changes are made.
