### ISSUE TITLE
Proposal to move Hydra battles in Coq to coq-community / to create a documented-examples project.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#108]
**Project name:** Hydra battles in Coq

**Initial author(s):** Pierre Castéran @Casteran

**Current URL:** https://framagit.org/casteran/hydra-battles-in-coq

**Kind:** documentation project composed of Coq scripts + LaTeX sources

**License:** CeCILL-B

**Description:** An exploration of some properties of Kirby and Paris' hydra battles, with the help of the Coq Proof assistant (draft).

**Status:** draft stage (complete but needs reviewing)

**New maintainer:** @Casteran with help of other coq-community members, e.g. @Zimmi48 

When we created coq-community, the goals were not just to provide a place for the long term maintenance of Coq packages but also for the collaborative writing of documentation around code, with this project as a first brick. Despite still being a draft, this project is now sufficiently complete to join coq-community as a first example of this documentation objective. It is our hope that other community members will help review the project, and especially the documentation part. Note also that for now this part is written in LaTeX, but it should be possible to experiment migrating to other formats that would be better suited to be viewed online as HTML pages.

**Comment by Zimmi48** [comment]
>Despite still being a draft, this project is now sufficiently complete to join coq-community as a first example of this documentation objective.

Instead of having one repository for Hydra battles and attempting to encourage the creation of other similar repositories of documentation by example, @Casteran suggests (and I support) creating a single monorepo which would gather all such documentation-by-example efforts. Hydra battles would be the first project to join this monorepo but it would later be joined by another similar project of @Casteran on fast exponentiation, and we would actively recruit new contributors, both for improving existing content and for adding new content / new topics.

There would be multiple advantages to this approach:
- there would be a shared website and a better visibility for each sub-project;
- there would be a shared editorial team which would go beyond the maintainers of each sub-project;
- discussions regarding technical or pedagogical options could be done in a single issue tracker, therefore allowing to move forward for all the documentation-by-example projects at once;
- it would be easier to add smaller sub-projects, for instance based on one clever proof technique shared by someone on a Coq forum or Coq-Club.

However, we need to find a good name and suggestions are welcome. For now, the best I can think of in English is "documented-examples". Maybe someone will think of some better name?

We will also need to form an editorial team, but it will probably be more easily done when the project has concretely started in coq-community.

**Comment by anton-trunov** [comment]
A great initiative! 

> However, we need to find a good name and suggestions are welcome. For now, the best I can think of in English is "documented-examples". Maybe someone will think of some better name?

Tutorials, perhaps?

**Comment by Casteran** [comment]
Proofs-and-comments ?

Pierre

**Comment by palmskog** [comment]
In the usual academic vernacular, I thought well-described examples were called "pearls"? Such as "functional pearls", "proof pearls", "formal pearls".

**Comment by anton-trunov** [comment]
Wouldn't this reuse create some confusion between community-driven "pearls" and the peer-reviewed ones?

**Comment by Casteran** [comment]
Hi,

  What about « documented contributions »  (or «  literate contributions », or «  commented contributions» ) ?

Best regards,

Pierre

**Comment by anton-trunov** [comment]
I like the "Hydra battles" name of the seed project -- it's very catchy.
If we follow suit, maybe something like "Coq tales"? :)
This alludes to having a narrative, not just dry code and is (imho) less formal name.

**Comment by Casteran** [comment]
Indeed, hydra battles are a metaphor of work with a proof assistant.
Obviously hydra’s heads represent the dramatically increasing number of sub-goals the user (Hercules) has to solve (chop off).

When Yves and I wrote « Coq’Art", we found it important to choose a catchy name for a not-so-easy-to-read book.

**Comment by Zimmi48** [comment]
I agree with the advantage of a catchy title. "Coq tales" is nice but the pun reminds the already two existing projects called "Coqtail" (see #119).

**Comment by Casteran** [comment]
When we went to Japan for organizing a Summer School, we met young enthusiastic people of the Tsukuba Coq User Group.
Among other activities, they published a series of booklets, each one dedicated to some topic, e.g. automata theory, and many of them illustrated in  manga style.
http://tcug.jp/books/2016-12/ <http://tcug.jp/books/2016-12/>   
http://tcug.jp/books/2014-12/ <http://tcug.jp/books/2014-12/>

Meeting these people was the main source of inspiration to propose this site, including the catchy presentation of non-trivial contents.

**Comment by palmskog** [comment]
Why not just "Hydra Battles" then (without any mention of Coq)? Let that be the meta-project name.

I also want to remind about a more serious topic: please consider another license than CECILL-B, since it is claimed by the FSF to be GPL-incompatible. CECILL-B would seemingly prevent us from distributing Hydra Battles in Coq in binary form together with a GPL-based project.

**Comment by Casteran** [comment]
> Why not just "Hydra Battles" then (without any mention of Coq)? Let that be the meta-project name.
> 
> 
    Yes, I thought also about « Hydras and company » . Any variation on the same theme would fit.
> I also want to remind about a more serious topic: please consider another license than CECILL-B, since it is claimed by the FSF to be GPL-incompatible. CECILL-B would seemingly prevent us from distributing Hydra Battles in Coq in binary form together with a GPL-based project.
> 
> 

Is the following license OK ? The contribution by Evelyne Contejean  (files src/rpo/*.v)  is already prefixed by

(* This program is free software; you can redistribute it and/or      *)
(* modify it under the terms of the GNU Lesser General Public License *)
(* as published by the Free Software Foundation; either version 2.1   *)
(* of the License, or (at your option) any later version.             *)

In this case, I can remove all the occurrences of CECILL-B in both contributions (hydras and addition chains).

**Comment by Zimmi48** [comment]
LGPL 2.1 is OK but far from the best license. See "What license to choose for a coq-community project?" in https://github.com/coq-community/manifesto#faq. If you can ask Evelyne if she would agree to relicense her work, then the most appropriate license would be the very permissive MIT license.

**Comment by Casteran** [comment]
The coq-community coq-art directory is also still licensed with Cecii-B. If Yves agrees, we should change it for MIT License ?

**Comment by palmskog** [comment]
@Casteran yes, changing to the MIT license would be helpful, and would also ensure we would have fewer headaches when distributing the Coq'Art code in various collections.

**Comment by Casteran** [comment]
Yves is OK. So I pushed a file LICENSE into coq-art/
Please check if it’s OK

Pierre

**Comment by Zimmi48** [comment]
FTR, while waiting for Evelyne's answer, @Casteran has relicensed the project to LGPL-2.1 which is not perfect but better than the (GPL-incompatible) CeCILL-B.

I suggest that we move forward and proceed to the transfer under the current license and the current name (Hydra Battles). If we hear back from Evelyne, we can still change the license later on, and if we wish, we can also rename the project to something else.

**Comment by Casteran** [comment]
I agree !
  I made a last push this morning, so there is no problem for the move.

  When it’s done, please tell me if the compilation (.v + .tex) works fine. I’m not sure my Makefile fits with the most accepted canons, and any improvement is welcome !
  Then I will put links to the new address in the README.md at gitlab’s site.

  By the way, two questions: 
    -  is it possible to maintain a link from community to a recent version of the pdf (150 pages) ?
    - I think it would be interesting to let readers propose solutions to exercises, projects (big exercises) and in general improvements on the development (scripts and doc).
      Which is the best way to do that ? PRs ?

  Thank for your help ! I will now read Github’s tutorials!

Pierre

**Comment by Zimmi48** [comment]
>is it possible to maintain a link from community to a recent version of the pdf (150 pages) ?

One possible way would be to auto-generate the PDF from the last version of the `master` branch. I'll look into how this can be done.

>Which is the best way to do that ? PRs ?

Yes, PRs are the best way I think (although they can also use the issue tracker if they wish). I'll create a draft of a contribution guide.

**Comment by Zimmi48** [comment]
The repository import is now done at https://github.com/coq-community/hydra-battles

Regarding the `Makefile`, the one in `src/` is pretty standard. The one at the root is partly out of date. The targets `clean` and `vo` probably do not work anymore since there is no longer any `CoqMakefile`.

**Comment by Casteran** [comment]
@Zimmi48 Thanks a lot !

CoqMakefile and _CoqProject are created by "make project", hence "make all" in the root Makefile.  
_CoqProject is quite often refreshed (addition or move of .v files). So, I used to call "make project" in many occasions.

But I agree there is certainly a better and more standard way to automatize the creation and update of these files, more specifically _Coqproject.  Of course, let us make this the most standard as possible.

**Comment by Casteran** [comment]
@Zimmi48   I tried a simplification in the clean-makefile branch. Hope it's OK.

**Comment by palmskog** [comment]
Since this repo is now part of coq-community (https://github.com/coq-community/hydra-battles), I'm closing this issue. Please continue any related discussion as issues in the repo.
