### ISSUE TITLE
Proposal to move High School Geometry to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#109]
**Project name:** High School Geometry

**Initial author(s):** Frédérique Guilhot

**Current URL:** https://github.com/thery/HighSchoolGeometry and https://github.com/coq-contribs/high-school-geometry

**Kind:** pure Coq library / formalization of mathematical theorems

**License:** LGPL-2.1-or-later

**Description:** This library is dedicated to high-shool geometry teaching. The axiomatisation for affine euclidean space is in a non analytic setting.

**Status:** Unmaintained since 2019

**New maintainer:** @thery 

This is a project whose earlier releases and website on gforge will soon disappear, as discussed [here](https://github.com/coq/opam-coq-archive/issues/1299). It was recently ported by to 8.11 by Laurent Théry, who graciously offered to transfer his repository to coq-community. 

@thery as per discussion the opam-archive issue, I have invited you to become a member of coq-community to allow your repository to be maintained here. Once you are a member, you should be able to transfer your repository to the `coq-community` organization on GitHub. Please let us know here if there are any issues.

**Comment by thery** [comment]
@palmskog ok I did the transform.it seems ok Just tell me what is left to be done.

**Comment by palmskog** [comment]
Thanks @thery. Since the repository transfer is done, I think we can close this issue. As for the next steps, we need to add some basic boilerplate and continuous integration for the repository, but I have opened coq-community/HighSchoolGeometry#1 for this purpose, so let's continue there.
