### ISSUE TITLE
Change maintainer of project Bertrand

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#113]
**Project name and URL:** https://github.com/coq-community/bertrand

**Current maintainer:** @herbelin 

**Status:** maintained

**New maintainer:** looking for a volunteer

As described by @Zimmi48 in #104, @herbelin is taking care of the coq-contribs, so a new maintainer is wanted for this project.

**Comment by thery** [comment]
I will take it ;-)

**Comment by palmskog** [comment]
Thanks @thery, this is appreciated. I will make you admin of the bertrand repo and update the metadata.

**Comment by thery** [comment]
how it works for the opam package?

**Comment by palmskog** [comment]
The metadata and settings are updated now, so I think we can close this issue, but feel free to ping me in another issue (or via Zulip or email) if something is unclear w.r.t. packaging/automation.
