### ISSUE TITLE
Proposal to move project coq100 to coq-community

### ISSUE THREAD

**Issue by jmadiot** [coq-community/manifesto#116]
**Project name:** coq-100-theorems

**Initial author(s):** Jean-Marie Madiot

**Current URL:** https://madiot.fr/coq100/  repository: https://github.com/jmadiot/coq100

**Kind:** web page + formalizations of a few mathematical theorems

**License:** MIT

**Description:** This is an appendix to Freek Wiedijk's web page on the "top 100" mathematical theorems, to keep track of the statements of the theorems that are formalised in Coq.

**Status:** maintained

**New maintainer:** I wish to continue to maintain if that's possible

**Comment by palmskog** [comment]
@jmadiot indeed you can continue to be the maintainer. Joining coq-community is not about transfer of control, but about extending possibilities for collaboration.

I have invited you to become a member of the coq-community organization. After you accept the invitation, you should be able to transfer the repo to the organization by using the "Settings" repo tab on GitHub.

**Comment by palmskog** [comment]
The repo is now available here: https://github.com/coq-community/coq100/
... and @jmadiot is admin of the repo. This means I think we can continue the discussion about the project in repo issues and PRs, so closing this.
