### ISSUE TITLE
Proposal to move project generic-environments to coq-community

### ISSUE THREAD

**Issue by aerabi** [coq-community/manifesto#121]
**Project name:** Generic Environments

**Initial author(s):** Emmanuel Polonowski

**Current URL:** https://github.com/coq-contribs/generic-environments

**Kind:** pure Coq library

**License:** LGPL

**Description:** Generic_Environments is a library which provides an abstract data type of environments, as a functor parameterized by a module defining variables, and a function which builds environments for such variables with any Type of type. Usual operations over environments are defined, along with an extensive set of basic and more advanced properties. Moreover, an implementation using lists satisfying and all the required properties is provided.

**Status:** Not maintained recently. The last available version works with Coq 8.10.

**New maintainer:** I volunteer: @aerabi

**Comment by Zimmi48** [comment]
Thanks for your interest in maintaining this project! I've proceeded to the transfer and invited you to join the organization.

There is an ambiguity on the exact license (is it LGPL-2.1-only, LGPL-2.1-or-later, LGPL-3.0...?). I'll send an e-mail to the author asking to clarify this and possibly to agree to relicense under one of our recommended licenses (cf. the corresponding FAQ item in the manifesto's README).

**Comment by Zimmi48** [comment]
The description is a bit long:
>Generic_Environments is a library which provides an abstract data type of environments, as a functor parameterized by a module defining variables, and a function which builds environments for such variables with any Type of type. Usual operations over environments are defined, along with an extensive set of basic and more advanced properties. Moreover, an implementation using lists satisfying and all the required properties is provided.

It should be shortened so that we can add `[maintainer=@aerabi]` to it.

**Comment by anton-trunov** [comment]
Since the transfer has been done, should we perhaps close this issue and move Théo's comment as a new issue to the generic-environments repo?

**Comment by Zimmi48** [comment]
I was planning to keep the issue open until we have heard back from the original author about the license (if you don't mind).

**Comment by anton-trunov** [comment]
Ah, sure, I didn't realize that, sorry for the noise.

**Comment by aerabi** [comment]
I have shortened the description. Will add the full description (which is the same as the article's abstract) as well as a link to the article to the README file later.

**Comment by Zimmi48** [comment]
The author has approved a change of license to the recommended MIT license.

**Comment by palmskog** [comment]
Since this repo is now part of coq-community (https://github.com/coq-community/generic-environments), I'm closing this issue. Please continue any related discussion as issues in the repo.
