### ISSUE TITLE
Proposal to move Autosubst version 1 to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#122]
**Project name:** Autosubst (version 1)

**Initial author(s):**  Steven Schäfer and Tobias Tebbi

**Current URL:** https://github.com/uds-psl/autosubst (the most recent version is found in the branch: https://github.com/uds-psl/autosubst/tree/coq86-devel)

**Kind:** pure Coq library

**License:** MIT

**Description:** A Coq library for parallel de Bruijn substitutions, useful when developing formal metatheory.

**Status:** unmaintained

**New maintainers:** @RalfJung and @co-dan 

This is based on a [discussion on Zulip](https://coq.zulipchat.com/#narrow/stream/237655-Miscellaneous/topic/Autosubst1.20and.20Autosubst2). 

The current proposal is that someone with access rights in the uds-psl organization transfers the above repo to the coq-community organization. @yforster can you confirm that you are able to do the transfer? If so, I can invite you to the coq-community organization.

**Comment by yforster** [comment]
I can confirm that I'm able to do the transfer.

**Comment by palmskog** [comment]
@yforster I sent you an invitation to join the organization. After you accept the invitation, feel free to transfer the repo whenever convenient.

**Comment by yforster** [comment]
Here you go: https://github.com/coq-community/autosubst

**Comment by RalfJung** [comment]
Thanks Yannick. :)

@palmskog what's next?

**Comment by palmskog** [comment]
@RalfJung @co-dan I have invited you to join the coq-community organization. Please accept the invitations and I can assign you to be admins for the repo.

**Comment by RalfJung** [comment]
Done.

**Comment by palmskog** [comment]
OK, since the repo has been transferred and maintainers now have admin access, let's close this issue and continue the discussion as repo issues.
