### ISSUE TITLE
Proposal to move project CoqEAL to coq-community

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#127]
**Project name:** CoqEAL

**Initial author(s):** according to the README, the authors are

  - Guillaume Cano (initial)
  - Cyril Cohen (initial)
  - Maxime Dénès (initial)
  - Anders Mörtberg (initial)
  - Damien Rouhling
  - Vincent Siles (initial)

**Current URL:** https://github.com/CoqEAL/CoqEAL

**Kind:** pure Coq library, which depends on the parmcoq plugin.

**License:** MIT

**Description:**

This libary contains a subset of the work that was developed in the context of the ForMath european project (2009-2013). It has two parts:
- theory (module CoqEAL_theory), which contains formal developments in algebra and optimized algorithms on mathcomp data structures.
- refinements (module CoqEAL_refinements), which is a framework to ease change of data representation during a proof.

**Status:** maintained

**New maintainer:** the current maintainers would stay in place.

This move was already proposed by one of the CoqEAL author (@CohenCyril) and approved by the others (@maximedenes @mortberg @drouhling) earlier this year (https://github.com/CoqEAL/CoqEAL/issues/33). I just discovered about this proposal and I think this is a good idea, given that the repository is quite significant but not very actively developed, is currently alone in its organization, already uses the coq-community templates, and could probably benefit from help from other coq-community members.

@CohenCyril If this is still something that you want to do, you should be able to proceed with the transfer.

**Comment by CohenCyril** [comment]
To the authors should be added @proux01 and @erikmd

**Comment by palmskog** [comment]
I think this is a good idea, and hopefully leads to eventual inclusion of CoqEAL into the Coq platform: https://github.com/coq/platform/issues/27

**Comment by spitters** [comment]
Nice! There's also an initiative to redo paramcoq based on metacoq, but I do not know what the status of that is.

**Comment by palmskog** [comment]
@CohenCyril @proux01 please let us know if we can help with anything that's blocking the transfer of the CoqEAL repo to the `coq-community` organization. I think there are some really nice synergies we can achieve after the transfer, such as having Nix cache-based CI for paramcoq that tests CoqEAL on every PR.

**Comment by proux01** [comment]
It seems we all agree on the transfert https://github.com/CoqEAL/CoqEAL/issues/33 so it's now just a matter of doing it.
@CohenCyril I don't have enough rights on CoqEAL repo, so I let you proceed.

**Comment by CohenCyril** [comment]
done!

**Comment by palmskog** [comment]
Thanks Cyril! I'm going to assume for now that Cyril and Pierre are the coq-community maintainers and put this in the repo description.

Let's close this issue and continue the discussion as CoqEAL issues.
