### ISSUE TITLE
Corn

### ISSUE THREAD

**Issue by spitters** [coq-community/manifesto#13]
## Move a project to coq-community ##

**Project name:** Corn

**Initial author(s):** Many

**Current URL:** https://github.com/c-corn/corn

**Kind:** pure Coq library

**License:** GPL

**Description:** The Coq Constructive Repository (previously) at Nijmegen.

**Status:** Maintained by Bas Spitters

**New maintainer:** Bas Spitters, but help is appreciated

**Comment by Zimmi48** [comment]
Thanks!
@spitters I've invited you to become a member of the coq-community GitHub organization. Once you accept the invitation, you should be able to transfer the repository corn and math-classes. To do this, go to the Settings of the repository, then click on Transfer at the bottom. Issues and pull requests will be kept, and URL redirections will be set up, so there shouldn't be any issue with people's forks, clones, or the OPAM packages which will still point to the old location until they are updated.

**Comment by spitters** [comment]
Thanks. Done. That was easy.
