### ISSUE TITLE
Proposal to move project vcs-prettify-symbols-mode to coq-community

### ISSUE THREAD

**Issue by mycroft92** [coq-community/manifesto#130]
**Project name:** vcs-prettify-symbols-mode

**Initial author(s):**  CJ Bell

**Current URL:** https://github.com/siegebell/vsc-prettify-symbols-mode

**Kind:** Visual Studio Code Plugin

**License:** MIT License

**Description:** Prettify symbols mode makes visual substitutions to your source code, e.g. displaying fun as λ, while never touching your code.

**Status:** Not maintained since 5 years. However two forks of the project are currently maintained (https://github.com/silver-dragon/vsc-prettify-symbols-mode) & (https://github.com/Pancaek/vsc-conceal) 

**New maintainer:** Looking for a volunteer.

**Comment by Zimmi48** [comment]
@Pancaek @silver-dragon Would you be interested in becoming the maintainers of this project within coq-community? Should we transfer one of your forks? How would you evaluate the differences between your two branches?

**Comment by rtetley** [comment]
If this is still relevant to people I could probably take a crack at maintaining it ?

**Comment by rtetley** [comment]
Okay will do !

**Comment by palmskog** [comment]
I guess what we are interested in is whether there should be a clean fork of https://github.com/siegebell/vsc-prettify-symbols-mode or it makes sense to try to collaborate with the vsc-conceal developer(s).

**Comment by rtetley** [comment]
Thanks for the clarification, I will do a bit of digging and let you know.

**Comment by pancaek** [comment]
Hi! To be honest, I don't really have the bandwidth to maintain vsc-conceal anymore, so I'd generally prefer to hand off the project in some way or another. It initially started as a way of merging some of the long-standing language support requests for people (namely LaTeX). It hasn't had any changes in logic from the original prettify-symbols-mode.

**Comment by rtetley** [comment]
Hi ! I'm more than willing to take over, just let me know what the next steps are ? Are we moving it to coq-community then ?

**Comment by palmskog** [comment]
@pancaek would you be willing to transfer the repository https://github.com/Pancaek/vsc-conceal to our GitHub organization [coq-community](https://github.com/coq-community)? If so, I can invite you to become an organization member so you can do the transfer. You could stay on as repository administrator if you like.

We prefer repository transfers over forks because this means repository issues and other metadata are kept, and there will be a redirect from the old location so people find the maintained repository.

**Comment by pancaek** [comment]
I would be glad to!

**Comment by palmskog** [comment]
The repository has been moved, and @rtetley now has admin access to the repo. Let's close this issue and continue any related discussion in repository issues: https://github.com/coq-community/vsc-conceal/issues
