### ISSUE TITLE
Proposal to move project Autosubst2 to coq-community

### ISSUE THREAD

**Issue by BinderDavid** [coq-community/manifesto#132]
**Project name:** Autosubst2

**Initial author(s):** Kathrin Stark

**Current URL:**  https://www.ps.uni-saarland.de/extras/autosubst2/

**Kind:** Automatic boilerplate generation for substitutions.

**License:** Unclear at the moment, the website is down and not archived with the wayback machine :(

**Description:** Similar to Autosubst, which is already a part of coq-community.  Has been described in a CPP 2019 article: https://dl.acm.org/doi/10.1145/3293880.3294101

**Status:** Unclear. It was available for download as an archive, but to my knowledge no public git repository exists. The website is currently offline as well, so there is no way to obtain the sources right now. It is possible that development continued for the `Coq a la carte` project: https://dl.acm.org/doi/10.1145/3372885.3373817 ?

**New maintainer:** looking for a volunteer

**Comment by palmskog** [comment]
@BinderDavid Autosubst2 is on GitHub and to my knowledge is currently maintained: https://github.com/uds-psl/autosubst2

Do you still want continue with the proposal?

**Comment by BinderDavid** [comment]
Oh, sorry. In that case that was an honest mistake on my part. I googled to superficially and only found the website which is currently offline. The proposal can therefore probably be closed.

**Comment by palmskog** [comment]
OK, then let's close this. For a usually up-to-date list of canonical links to Coq projects and resources (which included Autosubst2), see https://github.com/coq-community/awesome-coq
