### ISSUE TITLE
Proposal to move bignums to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#136]
**Project name:** Bignums

**Initial author(s):** Laurent Théry (@thery), Benjamin Grégoire, Arnaud Spiwack, Evgeny Makarov, Pierre Letouzey

**Current URL:** https://github.com/coq/bignums

**Kind:** Coq library and OCaml plugin

**License:** LGPL-2.1-only ("same as Coq")

**Description:** Provides BigN, BigZ, BigQ that used to be part of Coq standard library. Part of the Coq Platform, installed by default in the official Coq Docker images.

**Status:** part of Coq's CI and sometimes changed by Coq team members

**New maintainer:** @proux01 (and others?)

Based on the discussion and consensus in the latest Coq Call, I am proposing that Bignums transitions from the Coq GitHub organization to coq-community. The advantage is that coq-community has a process for maintaining a standalone repo, and many people who can do releases, merge PRs, etc.

@erikmd @proux01 would any of you consider being the maintainer of bignums in coq-community? I can help out with templates and other build boilerplate, but I can't be the maintainer myself.

@Zimmi48 should a representative from the Coq core team "officially" approve the move perhaps? Even before we have a maintainer lined up, or after? Grateful if you can help ping the right people.

**Comment by proux01** [comment]
@palmskog I'd happily (co)maintain bignums

**Comment by Zimmi48** [comment]
> @Zimmi48 should a representative from the Coq core team "officially" approve the move perhaps? Even before we have a maintainer lined up, or after? Grateful if you can help ping the right people.

I think we can consider the Coq Call decision to be sufficient, but we can ping the core team members anyway.

Present when the question was discussed and the decision was taken: @herbelin @JasonGross @mattam82 @ppedrot @SkySkimmer and @Zimmi48
Other core team members: @ejgallego @gares @maximedenes @silene @ybertot

**Comment by palmskog** [comment]
Dear Coq core team members, as Coq-community manager I think it would suffice if someone did a statement here roughly as follows:
> On behalf of the Coq core team, which currently manages the Bignums project, I approve of moving the Bignums repository to the coq-community organization on GitHub.

Then we could simply transfer the repo (I suggest Théo does this).

**Comment by Zimmi48** [comment]
Do you want this statement from someone else than me? (FWIW, I am a Coq core team member...) Maybe you want a statement from the project coordinator @mattam82?

**Comment by mattam82** [comment]
As agreed at the Coq Call:

On behalf of the Coq core team, which currently manages the Bignums project, I approve of moving the Bignums repository to the coq-community organization on GitHub.

**Comment by Zimmi48** [comment]
OK, let's do the transfer then!

**Comment by Zimmi48** [comment]
Done: https://github.com/coq-community/bignums

**Comment by Zimmi48** [comment]
FWIW, I've made @proux01 an admin, and I've removed the other collaborators because they all have write access to the repo already as coq-community members.

**Comment by palmskog** [comment]
Thanks everyone, I think we can now close this and continue discussions about Bignums as issues in the repo.

**Comment by erikmd** [comment]
> would any of you consider being the maintainer of bignums in coq-community? I can help out with templates and other build boilerplate, but I can't be the maintainer myself.

Thanks @palmskog for pinging me, and thanks @proux01 for your quick reply :+1:

Given that @proux01 and I are regular users of Bignums and that it's a core library within the Docker-Coq packaging (which is the reason why I did several releases in the recent past), I can propose to co-maintain Bignums, and thus be as the second co-maintainer (if @proux01 agree of course).

**Comment by Zimmi48** [comment]
We've updated the repository to mention the two co-maintainers, and I've given admin access to both of you.
