### ISSUE TITLE
Volunteer interim maintainers needed for VsCoq

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#140]
The Coq core team and Coq-community are looking for volunteer interim maintainers of the [VsCoq](https://github.com/coq-community/vscoq) project.

VsCoq is an extension of the [Visual Studio Code](https://code.visualstudio.com/) (VS Code) editor to support Coq source files and interaction with Coq. In a recent survey of Coq users, around [one third of respondents](https://coq.discourse.group/t/coq-community-survey-2022-results-part-ii/1746#coq-user-interfaces-7) reported that they use VS Code for Coq.

As described in [the public roadmap](https://github.com/coq-community/vscoq/wiki/VsCoq-1.0-Roadmap), VsCoq developers are currently focusing on building a new simplified architecture for VsCoq. This means that there are no longer any resources available for maintaining the current codebase.

VsCoq is an open source project available under the MIT license and developed in the [Coq-community organization](https://github.com/coq-community/manifesto) on GitHub. VsCoq is written in TypeScript and uses an XML-based protocol to communicate with Coq. Interim maintainers are expected to implement bugfixes, respond to pull requests and issues on GitHub, and release new versions of VsCoq on the [Visual Studio Marketplace](https://marketplace.visualstudio.com/) and [Open VSX](https://open-vsx.org/).

An important goal of interim maintenance is to provide a good experience for Coq users relying on VS Code for Coq while the new VsCoq architecture (and support for this architecture in Coq itself) is being developed and tested. However, interim maintainers should be aware that substantial parts of the current codebase are due to be replaced as the roadmap is implemented.

During their tenure, interim maintainers will be considered part of the [Coq Team](https://coq.inria.fr/coq-team.html) and credited for their work in release notes for Coq releases, for example [on Zenodo](https://doi.org/10.5281/zenodo.1003420).

Please respond to this GitHub issue with your motivation, and summary of relevant experience, for becoming an interim maintainer of VsCoq. The interim maintainer(s) will be selected from the issue responders by the Coq core team and Coq-community owners. Those not selected will still be encouraged to contribute to VsCoq in collaboration with the new maintainer(s).

**Comment by thery** [comment]
I am volunteer. I am usually vscoq on a daily basis but I have little knowledge of the current code base.

**Comment by palmskog** [comment]
Closing this since both new maintainers have been confirmed. Let's continue discussions about VsCoq in its GitHub repo.
