### ISSUE TITLE
Proposal to start project "Rosetta stone of meta-programming" in coq-community

### ISSUE THREAD

**Issue by yforster** [coq-community/manifesto#147]
**Rosetta stone of meta-programming:**

**Initial author(s):** @yforster @tlringer @ecranceMERCE @gares @MSoegtrop

**Current URL:** n/a

**Kind:** different examples of tactics, plugins, etc written in different meta-programming languages

**License:** MIT

**Description:**

**Status:** new project

**New maintainer:** @yforster

**Comment by Zimmi48** [comment]
I think since this is a new project, creating it here and having initial authors push to it would be explicit approval.

**Comment by palmskog** [comment]
@Zimmi48 but this is actually about transferring code from another repo to the new repo, and the previous repo has many authors.

**Comment by palmskog** [comment]
We now have approval for the contents of the repo [here](https://coq.zulipchat.com/#narrow/stream/373964-CUDW-2023/topic/Rosetta.20stone.20of.20extension.20languages/near/370339548). @yforster please go ahead and create the repo with initial content when convenient (hopefully with a reasonably descriptive and succinct name).

**Comment by MSoegtropIMC** [comment]
how about "tactic-rosetta-stone" as project name?

**Comment by palmskog** [comment]
The repo was created, so let's close this and continue discussions elsewhere, e.g., as repo issues on Zulip: https://github.com/coq-community/metaprogramming-rosetta-stone
