### ISSUE TITLE
Coq-ext-lib

### ISSUE THREAD

**Issue by spitters** [coq-community/manifesto#15]
## Move a project to coq-community ??? ##

There seems to be an overlap in goals between coq-community, the new std-lib and coq-ext-lib.
@gmalecha , @maximedenes It might make sense to coordinate.

**Project name:** coq-ext-lib

**Initial author(s):** Gregory M. Malecha

**Current URL:** https://github.com/coq-ext-lib/coq-ext-lib

**Kind:** pure Coq library

**License:** FreeBSD

**Description:**  A library of Coq definitions, theorems, and tactics.

**Status:** maintained by  Gregory M. Malecha

**Comment by Zimmi48** [comment]
@gmalecha has indeed expressed a lot of interest in stdlib2, see the issues raised here https://github.com/coq/stdlib2/issues and the discussions here https://gitter.im/coq/stdlib2.

**Comment by spitters** [comment]
It would be very interesting to know what @mattam82 and @gares think about the speed of type classes. They are both actively working on improving unification.

About HITs, there's progress, and we should probably start to consider how to include cubical methods into Coq in the future. I know @herbelin has been thinking about that.

**Comment by spitters** [comment]
Just noticed that this library is used in certicoq. Apparently a copy, not as an opam package.
@aa755 Do you know more?
https://github.com/PrincetonUniversity/certicoq/

**Comment by gmalecha** [comment]
I would imagine the reason is due to Windows and opam (they don't play nicely, right?).

**Comment by spitters** [comment]
My students in Software Foundations had no problem using opam on Windows.
Although most of them are using another OS.

**Comment by gmalecha** [comment]
Ok, Abhishek will probably know then.

**Comment by Zimmi48** [comment]
>My students in Software Foundations had no problem using opam on Windows.

Good to know. And then what editor would they use?

Note that the Windows installer of Coq 8.8.2 will include the option to install coq-ext-lib (among other addons) so it should allow all Window users to rely on it without trouble.

**Comment by spitters** [comment]
Either PG or coqide. I don't know of anyone using the windows installer, but I'll ask what they are using.
The whole installation went surprisingly smooth.

**Comment by aa755** [comment]
Thanks to @mattam82, we have switched to opam in the certicoq project. That local copy of coq-ext-lib should be deleted.

**Comment by Zimmi48** [comment]
There was no conclusion on moving coq-ext-lib to coq-community for now. We can reopen later this issue or a new one if needed.

**Comment by spitters** [comment]
coq-ext-lib fails to compile in 8.9 in opam (on my machine).
I'd suggest moving coq-ext-lib to CI, but I think that's related to this issue.

**Comment by Zimmi48** [comment]
It is already in Coq's CI... I'd say it is probably an issue of preparing a new opam release.

**Comment by gmalecha** [comment]
I haven't had a lot of time lately to maintain ExtLib so if it makes sense, I can move it to CoqCommunity. I would love to incorporate the ideas from it into stdlib2, but I don't have cycles right now and it seems like stdlib2 is moving in a different (better?) direction.

**Comment by liyishuai** [comment]
As a heavy user, I'm willing to maintain ExtLib.

**Comment by gmalecha** [comment]
That's great. I'd be happy to add you as a maintainer of the current repository in the meantime.

**Comment by Zimmi48** [comment]
@gmalecha I have invited you to join coq-community so you should be able to transfer the ext-lib repository as soon as you accept it. Just to clarify, should the new official maintainer be @liyishuai alone, or the both of you?

**Comment by liyishuai** [comment]
I'm now able to do the transfer. Should I read Gregory's previous comments as approving and proceed? We can update official maintainers anytime.

**Comment by liyishuai** [comment]
> Just noticed that this library is used in certicoq. Apparently a copy, not as an opam package.
> https://github.com/PrincetonUniversity/certicoq/

I've seen several @PrincetonUniversity projects that install dependencies from source rather than OPAM. It's more of a preference, not because OPAM doesn't work.

**Comment by gmalecha** [comment]
I'd like to stay on as a contributor, and I might get some cycles in the future to do more maintenance, but I won't be able to do active maintenance.

**Comment by liyishuai** [comment]
I've transferred the repository. @Zimmi48 could you grant Gregory and me admin access to https://github.com/coq-community/coq-ext-lib?

**Comment by Zimmi48** [comment]
Done.

**Comment by Zimmi48** [comment]
> I've seen several @PrincetonUniversity projects that install dependencies from source rather than OPAM. It's more of a preference, not because OPAM doesn't work.

Possibly also the influence of CompCert upon VST.

**Comment by Zimmi48** [comment]
I guess this issue can be closed now.
