### ISSUE TITLE
Proposal to move Parseque to Coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#153]
**Project name:** Parseque

**Initial author(s):** @gallais

**Current URL:** https://github.com/gallais/parseque

**Kind:** pure Coq library

**License:** GPL-3.0

**Description:** Total parser combinators in Coq, a port of [agdarsec](https://github.com/gallais/agdarsec) to Coq.

**Status:** maintained, but @gallais would like to transfer maintainership

**New maintainer:** @womeier, as per [this comment](https://github.com/WasmCert/WasmCert-Coq/issues/29#issuecomment-1810156725)

While the current license is GPL-3.0, @gallais indicated [here](https://github.com/WasmCert/WasmCert-Coq/issues/29#issuecomment-1810000871) that the project could be relicensed to a more permissive license to, e.g., avoid problems with depending on both this library and projects like MathComp that use CECILL-B that is incompatible with GPL-3.0. This would solve some licensing issues for [WasmCert-Coq](https://github.com/WasmCert/WasmCert-Coq/issues/29).

cc: @spitters

**Comment by palmskog** [comment]
@gallais @womeier our [recommended](https://github.com/coq-community/manifesto#best-practices) license for projects in Coq-community is the permissive MIT license. Is this license OK with you as the new license for Parseque after the transfer? 

If so, let me know here. I will then invite @gallais to the Coq-community organization so the repository can be transferred.

**Comment by gallais** [comment]
Yes, I'm happy with that.

**Comment by womeier** [comment]
@palmskog small correction: I just did maintenance work, should not be named as an original author.

**Comment by palmskog** [comment]
@gallais you should now be able to transfer the repo by going to the repo setting and the "Danger Zone" options there, by entering the `coq-community` organization name. One the transfer is done, I can take things from there.

**Comment by palmskog** [comment]
Since the repository has now been moved, I will close this issue and we can continue the discussion in issues and pull requests to the repo: https://github.com/coq-community/parseque
