### ISSUE TITLE
Proposal to create coq-notation-examples in coq-community

### ISSUE THREAD

**Issue by bcpierce00** [coq-community/manifesto#154]
**Project name:**

coq-notation-examples

**Initial author(s):**

Benjamin Pierce (bcpierce00)

**Current URL:**

None.

**Kind:** pure Coq library / OCaml plugin / extractable program / formalization of a mathematical theorem / ...

Collection of single-file Coq developments

**License:** MIT license

**Description:**

It's been proposed that it would be helpful for the Coq community to have a repository of "worked examples" showing best practices for using notations and custom entries.  

**Status:** 

Still in discussion stage, but there is already material to include once the repo is created.

**New maintainer:** looking for a volunteer 

I (Benjamin Pierce) can serve as initial maintainer if no one else wants to, but I would hope to involve a few more people over time.

**Comment by palmskog** [comment]
@bcpierce00 our [standard recommendation](https://github.com/coq-community/manifesto/?tab=readme-ov-file#best-practices) for license here is the MIT license, is this OK with you?

**Comment by bcpierce00** [comment]
Yes, that's fine!

**Comment by bcpierce00** [comment]
P.S.  Feel free to rename it just "notation-examples" instead of
"coq-notation-examples" for brevity.

**Comment by palmskog** [comment]
@bcpierce00 OK, so I think all our prerequisites are met here (e.g., we have an initial maintainer and an approved license). Feel free to transfer the repository to the `coq-community` organization whenever convenient, see repository settings under "Danger Zone". We can add new maintainers over time as they volunteer.

**Comment by palmskog** [comment]
> P.S.  Feel free to rename it just "notation-examples" instead of "coq-notation-examples" for brevity.

You can either rename the repository yourself, e.g., before the transfer, or I can do it once the transfer has been made.

**Comment by bcpierce00** [comment]
OK, so I should create the repo and transfer it?

**Comment by palmskog** [comment]
The repo is up and running with admin permissions: https://github.com/coq-community/notation-examples

If you add some Coq files, I can help up with setting up some basic continuous integration to check that the code builds (this is a requirement for joining Coq's CI).

**Comment by bcpierce00** [comment]
OK, I've added Test.v and a Makefile that compiles it.  Please feel free to
adjust anything I've done, if there's a way to do it that's more convenient
for you.
