### ISSUE TITLE
Proposal to move dedekind-reals to Coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#156]
**Project name:** dedekind-reals

**Initial author(s):** Andrej Bauer, Vincent Semeria

**Current URL:** https://github.com/andrejbauer/dedekind-reals

**Kind:** pure Coq library

**License:** MIT

**Description:** A formalization of Dedekind real numbers. Unlike the formalization of Dedekind reals in Coq's standard library, this formalization is based on Coq's `Prop`; a comparison can be viewed [here](https://github.com/coq/coq/blob/0aab3e0636fa07933daac7b3536e27dcda147dd5/theories/Reals/Abstract/ConstructiveReals.v#L12-L45).

**Status:** maintained by @andrejbauer, but proposed to be moved to Coq-community for more collaborative maintenance and preservation.

**Comment by andrejbauer** [comment]
I would like to thank @palmskog for making sure the library does not rot into oblivion. I am of course deligthed to have the library included in the Coq-community.

**Comment by andrejbauer** [comment]
I have transferred the ownership to Coq-community.

**Comment by andrejbauer** [comment]
I nominate @VincentSe to be a maintainer of the library, as he contributed large chunks of it and should be considered a co-author.

**Comment by palmskog** [comment]
Thanks @andrejbauer, since the transfer is done I will close this issue.

@VincentSe if you want to be a maintainer of the library, please let me know (e.g., here on GitHub) and I will add you as admin to the dedekind-reals repository.
