### ISSUE TITLE
maintainer of project X

### ISSUE THREAD

**Issue by proux01** [coq-community/manifesto#157]
**Project name and URL:**

**Current maintainer:**

**Status:**

**New maintainer:** looking for a volunteer 

If no volunteer are found, the project will be marked as unmaintained until a new one is found.

**Comment by Zimmi48** [comment]
Opened by mistake?

**Comment by Zimmi48** [comment]
Opened by mistake?

**Comment by proux01** [comment]
Oups, yes, thanks for noticing, I still don't fully master the issue generator.
