### ISSUE TITLE
Additional maintainer of projects math-classes and corn

### ISSUE THREAD

**Issue by proux01** [coq-community/manifesto#158]
**Project name and URL:** https://github.com/coq-community/math-classes https://github.com/coq-community/corn

**Current maintainer:** @spitters 

**Status:** mostly maintained by coq-community and coq developers for many years

**New maintainer:** looking for a volunteer 

If no volunteer are found, the project will be marked as unmaintained until a new one is found.

**Comment by Lysxia** [comment]
I volunteer to maintain math-classes and corn. I am experienced at authoring and maintaining Coq libraries (itree, QuickChick) and I personally find the topics of these two libraries interesting so this would be an opportunity to get more familiar with them. I don't have any grand plans, I would be happy to just keep these libraries from accumulating too many cobwebs.

**Comment by spitters** [comment]
@Lysxia that would be excellent! I can stay on as co-maintainer, as I know the libraries well.

**Comment by proux01** [comment]
> @Lysxia our basic requirements for maintaining projects are quite modest, essentially to respond to PRs, ensure compatibility with latest Coq `master`, and putting out releases/packages compatible with latest stable Coq. Like for QuickChick, there will be issues opened by Platform maintainers when it's time for a new release.

Note that in this particular case, math-classes and corn being in Coq CI, this can be a tad more demanding, since the requirement is to "continuously" remain compatible with the master branch of Coq. But that should remain a very modest requirement in practice. Of course, if it ever comes more convenient for you to handle upgrades in a more asynchronous way, you are free to opt out of Coq CI at any time.
 
> @proux01 do you think @Lysxia becoming a co-maintainer fully addresses this issue? If so, feel free to close it.

Sure, thanks @Lysxia for taking this and @palmskog for handling it so quickly.
