### ISSUE TITLE
Proposal to move Tricks in Coq to Coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#159]
**Project name:** Tricks in Coq

**Initial author(s):** @tchajed 

**Current URL:** https://github.com/tchajed/coq-tricks

**Kind:** pure Coq library / documentation

**License:** not clear, hopefully it can be relicensed to a free software license [allowed](https://github.com/coq-community/manifesto/blob/master/CONTRIBUTING.md#proposing-a-new-package) in Coq-community

**Description:** Some tips, tricks, and features in Coq that are hard to discover.

**Status:** maintained by @tchajed

**Comment by palmskog** [comment]
@tchajed if as per https://github.com/tchajed/coq-tricks/issues/7#issuecomment-2243128010 you are willing to move the project, we have two (hopefully small) hurdles:
- the project must use a license that is either approved as an open source license by OSI or considered a free software license by FSF. We usually propose to use MIT, but to allow people to copy code easily, [Unlicense](https://unlicense.org/) could be used also. A `LICENSE` file should be added to the repo.
- the repo should be transferred to the `coq-community` organization on GitHub. This can be done via repo settings / danger zone.

**Comment by tchajed** [comment]
I added a license (MIT for the code, CC0 for documentation) and did the transfer. Thanks!

Can you add a link on the website?

**Comment by tchajed** [comment]
Also would you mind giving me Owner or maintenance privileges in the new repo? GitHub gave me write access automatically but didn't preserve admin rights to change settings.

**Comment by palmskog** [comment]
Great that the transfer was done and a license was added, so this issue can be closed. If you mean adding a link at https://coq-community.org to coq-tricks I'll be happy to add this later today.

I will open a repo issue to discuss the deployment stuff. See http://coq-community.org/awesome-coq/ for an example of deploying the README.

**Comment by palmskog** [comment]
@tchajed you should have admin privileges now. It may be a good idea to set up basic protection for `master` branch, since otherwise organization members can write to it.

**Comment by tchajed** [comment]
Looks like basic protection is already there (transferred from the old repo) - force pushes might work but otherwise status checks must pass on another branch before merging.
