### ISSUE TITLE
proviola

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#16]
## Move a project to coq-community ##

**Project name:** proviola

**Initial author(s):** Carst Tankink @Carst-Tankink

**Current URL:** https://bitbucket.org/Carst/proviola-source

**Kind:** tool

**License:** GPL v3

**Description:** A tool to be able to replay the proofs when browsing a coqdoc-generated HTML file.

**Status:** Not maintained.

**New maintainer:** looking for a volunteer 

cc @JasonGross @mgrabovsky @yforster who have shown interest by having a fork on GitHub and @spitters @aa755 @siddharthist who have shown interest otherwise.

For those of you that do not already know about coq-community, have a look at the README at https://github.com/coq-community/manifesto. And sorry for the noise if you do not feel concerned (you can easily unsubscribe from this issue).

**Comment by siddharthist** [comment]
Could this functionality be integrated into `coqdoc`?

**Comment by spitters** [comment]
Aside, Agda seems to have pretty good tools for documentationÆ
https://agda.readthedocs.io/en/v2.5.4.1/tools/literate-programming.html

**Comment by JasonGross** [comment]
I've also been doing a bit of development on proviola at https://github.com/JasonGross/proviola-source (mainly for HoTT, which continues to use it, and occasionally runs into issues)

**Comment by Zimmi48** [comment]
@JasonGross Do you want to maintain this within coq-community? A convergence between various coqdoc-related tools, and in particular js-extensions (like coqdocjs and proviola) would be great but does not have to happen first. It could be a later step if someone is up for the task.

**Comment by yforster** [comment]
Regarding this later step, I once managed to create html files with both coqdocjs and proviola for a project and tried to write down what I did: https://gist.github.com/yforster/e7d73135aea3ef5e39e1e7272e53e568

I probably won't have time to continue on this, but maybe it can help for somebody who wants to continue at some point.

**Comment by JasonGross** [comment]
I will not have much time to devote to maintaining this, but I'm willing to be a maintainer.  (Ideally a co-maintainer, but I'm also willing to be sole maintainer.)

**Comment by palmskog** [comment]
@JasonGross great to hear about you assuming maintainership. If I might add a bit to this burden in the interest of the community: since there is a rich Mercurial commit history for Proviola in the BitBucket repo, could you try to import this to GitHub and add your changes on top? Note that BitBucket is killing off Mercurial support in just a few months, and will simply delete all Mercurial repositories.

For example, you could try to use the GitHub importer: https://help.github.com/en/github/importing-your-projects-to-github/about-github-importer

**Comment by palmskog** [comment]
Just in time before the disappearance of all Bitbucket Mercurial-based repositories, the Proviola code and issues have been migrated to [a GitHub repository](https://github.com/coq-community/proviola) in coq-community, with @JasonGross assigned as the maintainer. Hence, I'm closing this issue.
