### ISSUE TITLE
Proposal to move project Functional Data Structures and Algorithms in SSReflect to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#161]
**Project name:** Functional Data Structures and Algorithms in SSReflect

**Initial author(s):** @clayrat

**Current URL:** https://github.com/clayrat/fav-ssr

**Kind:** pure Coq library

**License:** MIT

**Description:** A port of https://functional-algorithms-verified.org to Coq/SSReflect using in particular the Equations plugin.

**Status:** maintained by @clayrat

Based on discussion in https://github.com/clayrat/fav-ssr/issues/21 I propose this project is transferred to Coq-community but remains maintained by its original author and maintainer. Coq-community members can assist with metadata and CI and other improvements to the project by submitting pull requests. Coq-community can also help the visibility of the project.

The transfer should be instantaneous and not interrupt any ongoing content changes inside the repository. @clayrat if this sounds good to you, please confirm here and I will invite you to Coq-community and you can transfer the repo (go to settings and then "Danger Zone").

**Comment by palmskog** [comment]
@clayrat please feel free to transfer the `fav-ssr` repo to the `coq-community` organization when convenient. You can do the transfer by going to repo settings on GitHub and then scrolling down to "Danger Zone".

**Comment by clayrat** [comment]
I confirm, let me add the new chapter first :)

**Comment by clayrat** [comment]
Done

**Comment by palmskog** [comment]
Great, let's continue the discussion in PRs and issues in the repo.
