### ISSUE TITLE
Proposal to move VsCoq repo to Coq organization and create VsCoq-legacy repo in Coq-community

### ISSUE THREAD

**Issue by gares** [coq-community/manifesto#162]
Currently coq-community/vscoq has two very distinct branches, one for the so called "vscoq legacy" code base and one for the so called "vscoq2" one, and two distinct set of maintainers for the two branches.

We propose to create a new coq-community/vscoq-legacy repository, move there the legacy branch, and relocate the rest to coq/vscoq as per discussion during this Coq call https://github.com/coq/coq/wiki/Coq-Call-2024-10-08

**Comment by palmskog** [comment]
Could existing maintainers for the `vscoq` repo (both vscoq2 and vscoq legacy parts) please comment on this proposal? Do you agree to the repo split and the move of vscoq2 part to the `coq` organization? @rtetley @huynhtrankhanh @thery @Blaisorblade

**Comment by huynhtrankhanh** [comment]
I agree, they should be split.

**Comment by rtetley** [comment]
100% they should be split.

**Comment by huynhtrankhanh** [comment]
They're now split let's just close
