### ISSUE TITLE
lemma-overloading

### ISSUE THREAD

**Issue by anton-trunov** [coq-community/manifesto#17]
## Move a project to coq-community ##

**Project name:** lemma-overloading

**Initial author(s):** Georges Gonthier (@ggonthier), Beta Ziliani (@beta-ziliani), Aleksandar Nanevski (@aleksnanevski) and Derek Dreyer (@drdreyer)

**Current URL:** https://github.com/coq-contribs/lemma-overloading

**Kind:** pure Coq library (based on SSReflect/mathcomp)

**License:** GNU GPL v3

**Description:** Hoare Type Theory libraries from [How to make ad hoc proof automation less ad hoc](https://software.imdea.org/~aleks/papers/lessadhoc/journal.pdf) paper. The project presents a series of design patterns for *canonical structure* programming that enable one to carefully and predictably coax Coq’s type inference engine into triggering the execution of user-supplied algorithms during unification, and illustrates these patterns through several realistic examples drawn from Hoare Type Theory. The project also contains a typeclasses-based re-implementation for comparison.

**Status:** not maintained (since 2016)

**New maintainer:** Anton Trunov (@anton-trunov)

**Comment by Zimmi48** [comment]
Thanks @anton-trunov! Since you @-mentioned the initial authors, I'll leave a few days in case they want to comment before proceeding with the transfer from coq-contribs.

**Comment by beta-ziliani** [comment]
I support the move. @anton-trunov, let me know if you need help. It might be the case it doesn't work anymore in recent versions of Coq. An alternative is to make it depend on [Unicoq](https://github.com/unicoq/unicoq/), which replaces Coq's unification algorithm with one that is more stable.

**Comment by Zimmi48** [comment]
@anton-trunov The project has now been transferred: https://github.com/coq-community/lemma-overloading
And I have invited you to join the coq-community organization.
As with other ex-coq-contribs, I will try to submit a PR setting up CI soon.
It would also be good to update the README, convert it to Markdown and create a format that can be shared by all coq-community projects (see also #3).

**Comment by Zimmi48** [comment]
(And don't forget to watch the repository not to miss incoming issues or pull requests.)

**Comment by anton-trunov** [comment]
Thanks a lot @Zimmi48.

>As with other ex-coq-contribs, I will try to submit a PR setting up CI soon.

That's cool! I'll fix compilation today.

>It would also be good to update the README, convert it to Markdown
Will do. For now, I'll try to stick to the format you proposed in the linked issue: short description, initial authors, current maintainer, license, supported versions of Coq...

**Comment by Zimmi48** [comment]
This can probably be closed now.
