### ISSUE TITLE
Proposition to move Keller and Lasson's paramcoq to coq-community

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/manifesto#20]
## Move a project to coq-community ##

**Project name:** paramcoq

**Initial author(s):** Chantal Keller (@ckeller) and Marc Lasson (@mlasson) 

**Current URL:** https://github.com/parametricity-coq/paramcoq
(the maintained version is https://github.com/aa755/paramcoq) 

**Kind:** OCaml plugin

**License:** ~~No explicit licence, we should ask the original authors~~ Now MIT

**Description:**
This plugin computes the n-ary parametricity transformation of a closed term.

**Status:** 
Main repository is abandoned, but @aa755 repository is active.

**New maintainer:**
- looking for a volunteer 

@aa755 and I already wrote to @ckeller and @mlasson, who both agreed to transition paramcoq to coq-community

**Comment by Zimmi48** [comment]
Great!
Let's first wait to solve the licensing issue: as per the rules of coq-community, paramcoq needs an open source license to migrate here.
Regarding the transfer, I can add @mlasson or any admin of the @parametricity-coq organization as a member of coq-community, to handle the transfer, or I can take care of it if someone adds me as an admin of parametricity-coq.
Regarding the maintainer, don't you or @aa755 want to be the principal maintainer to start with?

**Comment by spitters** [comment]
To what extend is this work superseded by the recent work on template coq?
https://template-coq.github.io/template-coq/

**Comment by ckeller** [comment]
Thanks again for the proposition. The MIT license has been added to the repository https://github.com/aa755/paramcoq .
Tell us if you need something else!

**Comment by Zimmi48** [comment]
Great! @ckeller Are you an admin of https://github.com/parametricity-coq/paramcoq? If yes, I can make you a member of @coq-community for you to transfer the repository or else you can make me an admin of @parametricity-coq and let me do the transfer. In any case, since we said that this would be the repository to be transferred, it will need to be synchronized with the commits that are only in https://github.com/aa755/paramcoq.

**Comment by Zimmi48** [comment]
@proux01: Will you be the principal maintainer of the project?

**Comment by spitters** [comment]
@ckeller @CohenCyril what's the relation to the work in templateCoq?
My understanding was that that one is supposed to replace paramcoq (in the future?)

**Comment by mlasson** [comment]
@Zimmi48 I mergerd the commit from master from @aa755 master branch. 
If you make me a member of co-community I'll transfer the ownership.

**Comment by proux01** [comment]
@Zimmi48: if @aa755 agrees to be, that's perfectly fine for me.
Otherwise, I'll do it (at least as long as we are using it through [CoqEAL](https://github.com/CoqEAL/CoqEAL)).

**Comment by Zimmi48** [comment]
@mlasson Done.
@proux01 @aa755 I can also add both of you to the organization if you want to continue to do some joint maintenance.

**Comment by proux01** [comment]
@Zimmi48 fine for me

**Comment by Zimmi48** [comment]
Great, thanks!
I've sent an invite to @proux01 (@CohenCyril and @mlasson are already members of coq-community as well). @aa755 let me know if I should send you an invite as well.

**Comment by Zimmi48** [comment]
@proux01 You should probably "watch" the repository https://github.com/coq-community/paramcoq to be made aware of incoming issues and pull requests.

**Comment by ejgallego** [comment]
Paramcoq now has a CI, it has been integrated in Coq's CI too, and IMHO it is looking pretty good, congrats!
