### ISSUE TITLE
Proposal to add Thomas Braibant and Damien Pous' ATBR

### ISSUE THREAD

**Issue by tchajed** [coq-community/manifesto#21]
## Move a project to coq-community ##

**Project name:** ATBR (Algebraic Tools for Binary Relations)

**Initial author(s):** Thomas Braibant & Damien Pous

**Current URL:** [coq-contribs/atbr](https://github.com/coq-contribs/atbr) as well as a [project page](http://proton.inrialpes.fr/~braibant/atbr/)

**Kind:** pure Coq library (has a small plugin for internal use)

**License:** LGPL 3

**Description:** tactics for deciding equations in Kleene algebra

**Status:** unmaintained

**New maintainer:** @tchajed

**Comment by Zimmi48** [comment]
Cool, @tchajed I'm sending you an invite to join the coq-community organization and I'm taking care of the transfer of the repository.

**Comment by Zimmi48** [comment]
Done. I'll follow up soon with a PR adding some CI.

**Comment by Zimmi48** [comment]
Hopefully, we can migrate this webpage as well as a second step so that it can be kept up-to-date.

**Comment by Zimmi48** [comment]
FTR, Christian Doczkal @chdoc said on Gitter on Dec 05 16:08
>atbr is no longer maintained as it has been superseded by the relation-algebra library (which uses derivatives rather than automata)

Also what they mean by "no longer maintained" is "no longer maintained by them", this echoes what you were saying in https://github.com/coq-community/atbr/pull/2 and https://github.com/coq/opam-coq-archive/pull/415:

>I think there's a followup library that basically supersedes ATBR

The relation-algebra is now maintained at https://github.com/damien-pous/relation-algebra and has recently joined Coq's CI.

**Comment by palmskog** [comment]
If the approach in the new library is fundamentally different, I think there would still be reason to preserve/maintain ATBR for comparison (and for people reading the original paper). But it may be a good idea to flag up very clearly in the ATBR README that the original author(s) consider it to be superseded. I can do a PR to this effect.

**Comment by Zimmi48** [comment]
Agreed.

**Comment by damien-pous** [comment]
Hi,
Christian Doczkal informed me about this thread.
Indeed, I do not plan to maintain ATBR since we restarted it in the relation-algebra library.
I guess Thomas Braibant won't maintain it either (he has been in the industry for a while now).
Nevertheless, I agree that it would be nice if it were to stay somewhere, for people willing to read the corresponding articles.
Best,
Damien
