### ISSUE TITLE
Proposal to move Huffman

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#28]
## Move a project to coq-community ##

**Project name:** Huffman

**Initial author(s):** Laurent Théry

**Current URL:** https://github.com/coq-contribs/huffman

**Kind:** extractable program

**License:** LGPL 2.1

**Description:** A verified, extractable function for Huffman coding and accompanying theory.

**Status:** Maintained by Coq devs so far.

**New maintainer:** Karl Palmskog

This is a relatively small but meaningful program verification project in Coq-contrib that should be ideal to use as a vehicle for defining best practices for code extraction and compilation (now that dune will support both Coq and OCaml). I'm also using this project for other work, so I volunteer to maintain in the short term - in particular, to make it compatible with Coq 8.9 and beyond.

**Comment by Zimmi48** [comment]
Thanks for proposing to maintain this project!

@thery As the initial author, are you OK with the move from coq-contribs to coq-community?

**Comment by Zimmi48** [comment]
I'll take no answer as a go-ahead.

@palmskog The repository has now been transferred.

**Comment by Zimmi48** [comment]
> sorry I've stupidly given my ok by replying to the email

I'm surprised that GitHub didn't show it. It is supposed to be possible to post a comment by e-mail...

**Comment by thery** [comment]
@Zimmi48 Maybe the reply address is too generic:   <notifications@github.com>

Here is the header of the reply:
========================================
Subject: Re: [coq-community/manifesto] Proposal to move Huffman (#28)
Date: Tue, 27 Nov 2018 13:39:00 +0100

**Comment by Zimmi48** [comment]
I don't think so. Might be worth reporting to GitHub staff since it looks like a bug...

**Comment by thery** [comment]
@Zimmi48 made the report.

**Comment by palmskog** [comment]
Thanks @Zimmi48 and @thery! Everything seems to work well now with the huffman repo after the move, so I'm closing this.
