### ISSUE TITLE
Initial authors vs. other authors of projects

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#29]
## Meta-issue ##

Our current `README.md` and `opam` script templates make a distinction between initial authors and maintainers. However, going forward, I think this categorization is too limited. For example, if maintainers do significant refactoring or make extensions to a project, they deserve author recognition as well.

I see two ways to solve this:

1. Make no distinction between initial authors and other authors in `README.md` and `opam`. This is not my preferred option, since I think it's valuable to know who the initial authors were.

2. Introduce a category in between initial authors and maintainers, say, "contributing authors". These authors get separate listing in `README.md` and may include the current maintainer. They are also listed (without qualifier) in `opam`.

**Comment by anton-trunov** [comment]
> 2. Introduce a category in between initial authors and maintainers, say, "contributing authors"

I'm in favor of this second option, but I'm not so sure about `opam` files. Mostly, I don't want the initial authors to think I'm taking the credit for their creative work. E.g. personally I would not mind to be listed in the authors after some significant change in the project, although it's hard to define "significant change".

**Comment by Zimmi48** [comment]
I think the "Maintainer" field is important to signal who is currently maintaining the package. However, I wouldn't mind dropping the "Initial" word and have "Authors" be a general field which can include maintainers who did "significant change" to the projects. And I suppose it can be the maintainers who decide when they want to be listed in this field...

**Comment by palmskog** [comment]
OK, how about we just add another boolean field `initial` to each author (besides `name`). Then there can potentially be some symbol next to initial authors' names. I just don't want that information to disappear. I will do a PR to this effect for concreteness.
