### ISSUE TITLE
Proposal to add Chapar

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#40]
## Move a project to coq-community ##

**Project name:** Chapar

**Initial author(s):** Mohsen Lesani, Christian J. Bell, and Adam Chlipala

**Current URL:** https://github.com/mit-plv/chapar

**Kind:** extractable program

**License:** MIT

**Description:** A collection of certified causally consistent distributed key-value stores

**Status:** Currently unmaintained.

**New maintainer:** Karl Palmskog

**Comment by palmskog** [comment]
@MohsenLesani do you have access to transfer the repository on GitHub, or do you know who does?

**Comment by Zimmi48** [comment]
@siegebell or @achlipala being the other authors could also confirm if they are OK with the move to coq-community and if they have admin access on the repository to transfer it.

(I remind that the goals of coq-community are exposed in the README of this repository if any of the authors wants to learn more on the context.)

(@JasonGross might also know who has admin access on the repositories in the mit-plv organization and might be quicker to react...)

**Comment by achlipala** [comment]
Thanks for the interest in the project!  @MohsenLesani was indeed the primary author, so I would hope to have his blessing before a move of this kind.  I can confirm that we haven't been making any effort to maintain the code, so it is in principle a good thing to have both someone else take over and a mechanism put in place to help with future transitions.

**Comment by palmskog** [comment]
@achlipala I have been in contact with @MohsenLesani in person and via email. Hopefully you should receive a mail from him soon.

**Comment by palmskog** [comment]
For completeness, my main interest in the project is to use it as a benchmark when investigating various proof engineering techniques, like faster regression proving. I'm not looking to extend it, just make it run smoothly with a recent Coq version.

**Comment by palmskog** [comment]
Thanks to @achlipala and @MohsenLesani, this repository has now been moved, and I will try to document some of the hurdles we had with GitHub repository transfers to make this smoother in the future. Thanks also to @Zimmi48 for support. Closing this issue.
