### ISSUE TITLE
Move zorns-lemma and topology to coq-community.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#43]
## Move a project to coq-community ##

**Project name:** `zorns-lemma` and `topology`

**Initial author(s):** Daniel Schepler @dschepler

**Current URL:** https://github.com/coq-contribs/zorns-lemma and https://github.com/coq-contribs/topology

**Kind:** pure Coq library

**License:** LGPL-2.1-or-later

**Description:** This library develops some basic set theory. / This library develops some basic concepts and results of general topology.

**Status:** in coq-contribs; recent maintenance was done by @amiloradovsky.

**New maintainer:** Andrew Miloradovsky @amiloradovsky

**Comment by amiloradovsky** [comment]
OK. Thanks for the trust. Will try to do my best to keep these actual.

**Comment by Zimmi48** [comment]
@amiloradovsky The repositories have been transferred and you've been invited to join the organization. We'll try to help you setup continuous integration and other standard files using our usual [templates](https://github.com/coq-community/manifesto/tree/master/templates).

**Comment by amiloradovsky** [comment]
@Zimmi48 OK. So now I should assemble the `meta.yml`, generate the files from `{,.}*.mustache`, and put them under version control, like [this](https://github.com/amiloradovsky/zorns-lemma/tree/meta.yml)?

**Comment by Zimmi48** [comment]
Indeed, like this :smile:  If you open a PR with your changes on the zorn repo, I'll add some inline comments for small nits. The CI setup in topology might require some additional work to make it work, given the additional dependency. I'll provide a hand. (BTW, we generally delete the legacy `description` file once the `meta.yml` file has been added.)

**Comment by amiloradovsky** [comment]
OK. Here is the PR: https://github.com/coq-community/zorns-lemma/pull/2

**Comment by amiloradovsky** [comment]
And this is the draft for Topology: https://github.com/coq-community/topology/pull/3

**Comment by Zimmi48** [comment]
Good, I'll have a look at them tomorrow. BTW, you probably want to start "watching" the two transferred repositories.

**Comment by Zimmi48** [comment]
Let's close this now and track the rest of the work in the corresponding PRs.
