### ISSUE TITLE
Move reduction-effects plugin to coq-community

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#51]
## Move a project to coq-community ##

**Project name:** reduction-effects

**Initial author(s):** Hugo Herbelin (@herbelin)

**Current URL:** https://github.com/herbelin/reduction-effects

**Kind:** OCaml plugin

**License:** LGPL 2.1 (to clarify if this is "or later")

**Description:** A Coq plugin to add reduction side effects to some Coq reduction strategies

**Status:** has not been maintained since its creation

**New maintainer:** Jason Gross (@JasonGross)

See coq/coq#9692 for context. The intent is to also add the plugin to Coq's CI to make sure it is kept compatible with the latest versions of Coq, and to add it to the Windows installer.

@herbelin Can you confirm if you are OK with this plan? (and also if the license should be interpreted as LGPL-2.1-or-later?)

**Comment by liyishuai** [comment]
Any updates?
I've made the plugin usable in herbelin/reduction-effects#2 and am willing to comaintain this project.

**Comment by Zimmi48** [comment]
Hugo is overloaded in the current period, so I am not surprised he didn't answer. I'm going to see him today and ask him directly.

**Comment by Zimmi48** [comment]
I did this and he told me he would look into this but apparently he didn't do it yet. I'll ping him again when I get the chance.

**Comment by herbelin** [comment]
Thanks a lot @liyishuai. I'm ok with the coq-community plan. If I understand correctly, I just have to follow the instructions at https://help.github.com/en/articles/transferring-a-repository, which I could then do whenever I get your confirmation.

**Comment by Zimmi48** [comment]
:+1:

**Comment by Zimmi48** [comment]
@herbelin has done the transfer already.
@liyishuai and @JasonGross you have been invited to join the coq-community organization.

**Comment by Zimmi48** [comment]
Everything is in place now.
