### ISSUE TITLE
Move ALEA to Coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#55]
## Move a project to coq-community ##

**Project name:** ALEA

**Initial author(s):** Christine Paulin-Mohring, David Baelde, and Pierre Courtieu

**Current URLs:** https://www.lri.fr/~paulin/ALEA/alea-v8.tgz https://github.com/EasyCrypt/certicrypt/tree/master/ALEA https://github.com/hivert/Coq-HookLength/tree/master/ALEA/ https://github.com/hivert/Coq-Combi/tree/master/3rdparty/ALEA https://github.com/coq-contribs/random

**Kind:** pure Coq library

**License:** unknown

**Description:** A library for reasoning on randomized algorithms. Likely outdated now by more modern libraries such as Polaris, but interesting for its applications (CertiCrypt). More about the library and links to related papers: https://www.lri.fr/~paulin/ALEA/

**Status:** unmaintained since 2013

**New maintainer:** looking for a volunteer

**Comment by anton-trunov** [comment]
@volodeyka and I are volunteering to maintain this project. In fact, we already make it compile with a recent Coq version: https://github.com/anton-trunov/alea. If we could get a go-ahead from the original authors (CC @Matafou), then I'd transfer the ownership to Coq-Community.

**Comment by palmskog** [comment]
This is great, I think it's useful both as a paper artifact and as a step towards getting CertiCrypt working again. One property that perhaps @Matafou could comment on is the license. According to [this file](https://github.com/coq-contribs/random/blob/master/LICENSE), the license seems to be either `LGPL-2.1-only` or `LGPL-2.1-or-later`, but unclear which one.

**Comment by palmskog** [comment]
@anton-trunov since parts of ALEA seem to be in the [Random](https://github.com/coq-contribs/random) Coq contrib, maybe it's better to transfer the contrib repo to Coq-community and then add your changes there? Otherwise, the contrib should be marked as obsolete once another repo lives here.

**Comment by Zimmi48** [comment]
> Otherwise, the contrib should be marked as obsolete once another repo lives here.

Indeed. Given that there isn't much history to preserve over there, I was indeed considering that we could archive the contrib after the transfer.

**Comment by Matafou** [comment]
Hi,
I am currently asking the two other authors. David agreed. Still waiting for Christine's answer, which I expect to be positive as well.

Regarding license I have no idea which one is actually legitimate.

**Comment by Matafou** [comment]
Ho and my answer is positive as well of course. Thank you!

**Comment by anton-trunov** [comment]
Awesome, thank you very much @Matafou for your permission and for asking your coauthors about this matter!

@palmskog @Zimmi48 Great proposal, I had missed the reference to Random before. There is just one little thing -- it's the end of @volodeyka's internship and I'm not sure he has time to work on it this year. Maybe we could finish the transfer and move the suggestion as an issue. Then at a less hectic time for both of us, we could fix it and take care of Random in coq-contribs. What do you think?

**Comment by Zimmi48** [comment]
> Maybe we could finish the transfer and move the suggestion as an issue.

I am not sure to understand what you propose. If we decide to transfer your version of ALEA, then it's fine. I'll just archive the random contrib with a link to the appropriate version, as it has been done before.

**Comment by palmskog** [comment]
If my reading of the Random contrib metadata is correct, it's actually based on the original (2007) release of ALEA and not the expanded one from 2013. Hence, I think it probably makes more sense to archive the contrib than to transfer it. Consequently, I think we can just move Anton's repository to Coq-community right now.

@Matafou if the license is not 100% clear, is there any chance you and the other authors would agree to relicense ALEA to a more simple or recent license, such as the MIT license or `LGPL-3.0-or-later`? For example, I believe Yves Bertot switched to MIT (due to its simplicity) for the Semantics project before its move to Coq-community.

**Comment by anton-trunov** [comment]
A minor remark: the ported version of ALEA is bigger than the Random contrib in terms of lines of code: 11499 vs 8257.

**Comment by anton-trunov** [comment]
@Zimmi48 I took a closer look at the Random contrib and now I'm in favor of just a simple transfer of the ported ALEA repo.

**Comment by anton-trunov** [comment]
Hi @Matafou! Is there any feedback from your co-authors on transferring ALEA to coq-community? It would be nice to have ALEA published to support the upcoming transfer of Certicrypt as per https://github.com/coq-community/manifesto/issues/56

**Comment by palmskog** [comment]
Transfer is now done: https://github.com/coq-community/alea

So, closing this issue.
