### ISSUE TITLE
Proposition to move Laurent Théry's contribution Bertrand

### ISSUE THREAD

**Issue by herbelin** [coq-community/manifesto#6]
## Move a project to coq-community ##

**Project name:** Bertrand

**Initial author(s):** Laurent Théry

**Current URL:** https://github.com/coq-contribs/bertrand

**Kind:** formalization of a mathematical theorem / program correctness

**License:** LGPL 2.1

**Description:** A proof of correctness of the algorithm as described in `The Art of Computer Programming: Fundamental Algorithms` by Knuth, pages 147-149.

**Status:** formerly maintained in [coq-contribs](https://github.com/coq-contribs/)

**Previous maintainer:** matej.kosik@inria.fr

**New maintainer:** Hugo Herbelin

**Comment by Zimmi48** [comment]
The repository has now be transferred here: https://github.com/coq-community/bertrand
To-do:
- [ ] Setup CI
- [ ] Update the OPAM package

**Comment by Zimmi48** [comment]
https://github.com/coq-community/bertrand/pull/4 introduces an opam file in the repository that should be a good basis for submitting updates to the Coq package index.
