### ISSUE TITLE
Move the exact-real-arithmetic contrib to coq-community.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/manifesto#64]
## Move a project to coq-community ##

**Project name:** exact-real-arithmetic

**Initial author(s):** Jérôme Creci

**Current URL:** https://github.com/coq-contribs/exact-real-arithmetic

**Kind:** pure Coq library

**License:** LGPL-2.1

**Description:**  This contribution contains a proof of correctness of some exact real arithmetic algorithms from the PhD thesis of Valérie Ménissier-Morain

**Status:** last commit was two years ago

**New maintainer:** @ybertot + @magaud (?)

This issue is a follow-up of the coqdev thread "corrections to a contrib : exact-real-arithmetic".

**Comment by ybertot** [comment]
I won't have time to work on it before a few days.

**Comment by Zimmi48** [comment]
Sure, no rush.

**Comment by Zimmi48** [comment]
@ybertot Should we proceed with transferring this project now?

**Comment by Zimmi48** [comment]
@ybertot Should we still proceed to transfer this project with you as maintainer (not a very time-consuming task in general) or should we label this as looking for a maintainer?

**Comment by ybertot** [comment]
I am worried about getting permission from the initial author, and never got around to doing it.  What is your opinion?

**Comment by Zimmi48** [comment]
> What is your opinion?

Legally speaking, you don't need to obtain permission because this is properly licensed as free software.
Morally speaking, you don't need to obtain permission either because this was formerly a contrib, thus the initial author already intended for this project to be maintained by others.
Informing the initial author of the move is nice, but could be done as a later step.

**Comment by Zimmi48** [comment]
FTR I'm waiting on your "go" before actually performing the transfer.

**Comment by ybertot** [comment]
Yes, go. I will organize myself to work on it in the next few weeks.

**Comment by Zimmi48** [comment]
Repository transferred, and you've been made an admin. I'll let you close this issue.

**Comment by magaud** [comment]
Can I be a (co-)maintainer for the development as well ?

**Comment by Zimmi48** [comment]
Glad to hear back from you @magaud! I've just sent you an invitation to join coq-community.

**Comment by Zimmi48** [comment]
@magaud I've added you to the maintainers of this repo. Should this issue be closed now?
