### ISSUE TITLE
 Proposition to move Pierre Letouzey's contribution Stalmarck

### ISSUE THREAD

**Issue by herbelin** [coq-community/manifesto#7]
## Move a project to coq-community ##

**Project name:** Stalmarck

**Initial author:** Pierre Letouzey

**Current URL:** https://github.com/coq-contribs/stalmarck

**Kind:** extractable program

**License:** LGPL 2.1

**Description:** A two-level approach to prove tautology using Stalmarck's algorithm.

**Status:** formerly maintained in [coq-contribs](https://github.com/coq-contribs/)

**Previous maintainer:** matej.kosik@inria.fr

**New maintainer:** Hugo Herbelin

**Comment by Zimmi48** [comment]
The repository has now be transferred here: https://github.com/coq-community/stalmarck
To-do:
- [ ] Setup CI
- [ ] Update the OPAM package

**Comment by Zimmi48** [comment]
https://github.com/coq-community/stalmarck/pull/2 and https://github.com/coq-community/stalmarck/pull/4 were submitted to add CI and opam packages in the repository.
