### ISSUE TITLE
VsCoq

### ISSUE THREAD

**Issue by maximedenes** [coq-community/manifesto#72]
## Move a project to coq-community ##

**Project name:** VsCoq

**Initial author(s):** C. J. Bell (@siegebell)

**Current URL:** https://github.com/siegebell/vscoq

**Kind:** UI for Coq

**License:** MIT

**Description:** A VSCode extension for Coq

**Status:** unmaintained (last commit in 2017, unmerged fixes / ports to newer Coq versions)

**New maintainer:** I volunteer

**Comment by maximedenes** [comment]
Note: many contributors are maintaining patches on their VsCoq fork, but they are not merged currently due to the main repo being inactive, which is a pity. The `master` branch at https://github.com/maximedenes/vscoq collects such patches (from other authors) that make VsCoq compatible with the current Coq `master`, for example.

**Comment by Zimmi48** [comment]
Another note: @maximedenes has tried to reach out to @siegebell but without success so far.

Our contributing guide has an explicit process for this case:

>The main authors of the package must either consent to this move or be completely unresponsive. Therefore, once a project is proposed, we will open an issue at the original project URL (or send an e-mail when this option is not available) to try to get consent or at least confirm the unresponsiveness.

Following this, I opened an issue on the vscoq repository: siegebell/vscoq#170.

**Comment by maximedenes** [comment]
@Zimmi48 can I proceed and create the vscoq repo?

**Comment by Zimmi48** [comment]
Yes, I think we have left enough time.

**Comment by Zimmi48** [comment]
FTR The project was created (https://github.com/coq-community/vscoq).

@maximedenes I just noticed that the previous project had documentation in its wiki (in fact the README still redirects to the old README) but this wiki has not been duplicated in the new repository. You can easily do so given that GitHub wikis are just normal git repositories, so it's just a matter of activating the wiki, retrieving the old wiki history and force-pushing it.

**Comment by maximedenes** [comment]
Yes, thanks. I believe part of this documentation has been moved to the Coq repo, and other parts will need updated. I'll look at it once the most pressing issues are addressed.

**Comment by Zimmi48** [comment]
@maximedenes Should we close this and track the remaining issues related to the transfer on the vscoq repository?
