### ISSUE TITLE
Proposition to move Milad Niqui's Stern-Brocot construction of rational numbers

### ISSUE THREAD

**Issue by herbelin** [coq-community/manifesto#8]
## Move a project to coq-community ##

**Project name:** QArithSternBrocot

 **Initial author(s):** Milad Niqui

**Current URL:** https://github.com/coq-contribs/qarith-stern-brocot

**Kind:** pure Coq library

**License:** LGPL 2.1

**Description:** Developement of rational numbers as finite binary lists and defining field operations on them in two different ways: strict and lazy. 

**Status:** formerly maintained in [coq-contribs](https://github.com/coq-contribs/)

**Previous maintainer:** matej.kosik@inria.fr

**New maintainer:** Hugo Herbelin

**Comment by Zimmi48** [comment]
The repository has now be transferred here: https://github.com/coq-community/qarith-stern-brocot
To-do:
- [ ] Setup CI
- [ ] Update the OPAM package
