### ISSUE TITLE
Proposal to move project hoare-tut to coq-community

### ISSUE THREAD

**Issue by k4rtik** [coq-community/manifesto#84]
**Project name:** Tutorial on Hoare Logic

**Initial author(s):** Sylvain Boulme

**Current URL:** https://github.com/coq-contribs/hoare-tut/

**Kind:** pure Coq library / tutorial

**License:** LGPLv3

**Description:** A Tutorial on Reflecting in Coq the generation of Hoare proof obligations

**Status:** Unmaintained (see: https://github.com/coq-contribs/hoare-tut/pull/1#issuecomment-553979288)

**New maintainer:** me

**Comment by Zimmi48** [comment]
Thanks for proposing to maintain this contrib.

Cc @boulme (for your information)

**Comment by Zimmi48** [comment]
Repository has been transferred.

**Comment by k4rtik** [comment]
Thanks @Zimmi48
