### ISSUE TITLE
Proposal to move project semantics to coq-community

### ISSUE THREAD

**Issue by k4rtik** [coq-community/manifesto#85]
**Project name:** Semantics

**Initial author(s):** Yves Bertot

**Current URL:** https://github.com/coq-contribs/semantics

**Kind:** pure Coq library / formalization of PL semantics

**License:** LGPL

**Description:** A survey of semantics styles, from natural semantics through structural operational, axiomatic, and denotational semantics, to abstract interpretation.

**Status:** Unmaintained (see: https://github.com/coq-contribs/hoare-tut/pull/1#issuecomment-553979288)

**New maintainer:** me

**Comment by Zimmi48** [comment]
Thanks for proposing to maintain this contrib.

Cc @ybertot FYI. BTW @ybertot could you tell us which version of the LGPL it is intended to be? Unfortunately, the contrib submission form that was available at the time of the submission was pretty sloppy and only allowed a choice between LGPL and BSD-like without further specifications. Nowadays, we generally recommend choosing LGPL 3.0-or-later.

**Comment by ybertot** [comment]
Concerning the license, I chose that one when making my contribution available because I thought it was the most permissive one (but I did not spend too much time thinking about it).  But today I went to read LGPL-3.0 and there are too many sentences I don't understand.  I don't understand what they mean by "convey", I don't understand when people can do anything with it or not.

@Zimmi48, would it make sense to switch to MIT license, before any substantial contribution by anybody else?

**Comment by Zimmi48** [comment]
Yes, it would.

**Comment by ybertot** [comment]
So I suggest the license is moved to MIT.

**Comment by ybertot** [comment]
I approve this move from coq-contrib to coq-community.  I will occasionally contribute.  I am happy that @k4rtik volunteers to maintain it.

**Comment by k4rtik** [comment]
Thanks, @ybertot!

Thanks @Zimmi48 for suggesting it.

**Comment by Zimmi48** [comment]
Repository now transferred to coq-community. @k4rtik You've been made a member of coq-community and an admin of semantics (and hoare-tut). You should have received three invitation e-mails but only the first one (invitation to join coq-community) matters: by accepting this one, you will be accepting the others.

Please change the license of semantics to MIT as wished by Yves as a first step, and link to Yves's comment above in the commit message.

**Comment by k4rtik** [comment]
Done! Closing this now.

**Comment by Zimmi48** [comment]
I suggest you additionally delete the `description` file, which still contains the reference to the LGPL license, and move the relevant information to a new `meta.yml` file, which can be used to generate a number of files from the templates available at https://github.com/coq-community/templates. We can help with this if you need (documentation on how to use them is not great yet).

**Comment by k4rtik** [comment]
Sorry, I intended to modify the description file but missed it; but certainly more needs to be done. Will do, thanks.
