### ISSUE TITLE
Proposal to move JMLCoq to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#86]
**Project name:** JMLCoq

**Initial author(s):** Hermann Lehner (http://people.inf.ethz.ch/lehnerh/ http://www.hermann-lehner.com)

**Current URL:** http://jmlcoq.info (http://jmlcoq.info/index_files/JMLCoq.tar.gz)

**Kind:** pure Coq library

**License:** MIT

**Description:** Coq formalization of the Java Modeling Language.

**Status:** unmaintained since 2011

**New maintainer:** looking for a volunteer

There are many Coq formalizations of fragments of Java floating around, but this one is quite well documented (a whole thesis) and has applications in runtime checking, and thus may be interesting to maintain for the long term. It seems likely the author should agree to license this work under an open source license, since the final thesis paragraph reads: 
> We hope that our work will be of good use in the research community and help to motivate others to choose a more formal approach to software verification.

**Comment by Zimmi48** [comment]
I suggest reaching out to the author and asking them about open source licensing even before (and independently of) finding a volunteer to maintain it as part of coq-community.

**Comment by palmskog** [comment]
I contacted the JMLCoq author, and he said that he is willing to license the project under the MIT license. I think he will also update the website and code archive with this information soon.

**Comment by palmskog** [comment]
To extract some pieces I needed for other work, I updated the JMLCoq code to compile with Coq 8.9 and later: https://github.com/palmskog/jmlcoq

While I don't have plans to maintain the repo, it might be a good to host it in coq-community to find increase the chances of finding a maintainer.

**Comment by palmskog** [comment]
Repository has now been moved to coq-community (https://github.com/coq-community/jmlcoq), so closing this.
