### ISSUE TITLE
Social media / Twitter account

### ISSUE THREAD

**Issue by ejgallego** [coq-community/manifesto#89]
Hi folks,

the [discussion here](https://gitter.im/coq-community/Lobby?at=5e18d545a74ac8537789175c) made me wonder about the communication strategy of Coq Community, and in particular presence on social media.

Personally, I think that having a (shared) twitter account would be a great idea; twitter is of course not perfect but a lot of researcher and potential audience is already there; it is lightweight; and I find the S/N ratio to be pretty good.

WDYT folks.

p.s: just in case I have reserved the `CoqCommunity` and `coq_community` on twitter as the sooner I write about this the sooner some joker would register them.

**Comment by anton-trunov** [comment]
Emilio, I fully support that! IMVHO, professional accounts like the intended one could make Twitter a better place.

**Comment by palmskog** [comment]
I'm fine with there being a Twitter account, but I'll probably stay away myself unless we can figure out some automation for posting about new releases and the like.

**Comment by ejgallego** [comment]
I guess more input here is needed, at least from @Zimmi48 , @herbelin , @ybertot (and who else? )

A technical detail needed to implement this is what should the mail address associated to the twitter account be. Ideally we would setup an institutional email `@inria.fr` ? Using gmail, etc... poses significant risk in case of account blockage.

**Comment by herbelin** [comment]
I must confess I'm not familiar with using twitter, so I don't feel competent to answer, but that looks like a good idea.

**Comment by Zimmi48** [comment]
@ejgallego Do you think it makes sense to use a private mailing list as the e-mail address for this Twitter account? If yes, then we can set up one on Inria's sympa server.

Note that here it seems you are proposing a "coq-community" Twitter account, but to me it would make more sense to just focus on a "Coq-lang" Twitter account (which could indeed be community-managed). Thus similar to https://twitter.com/OCamlLang.

**Comment by palmskog** [comment]
I also think a general Coq Twitter account, managed by (someone at) INRIA, makes more sense.

**Comment by ejgallego** [comment]
Indeed a possibility would be to have a Coq "marketing" team, we have discussed this a few times; I am OK with that [and added an item for the next Coq Call] but keep in mind that putting that under the Coq umbrella has some downsides, in particular the management of the account may become less agile, etc...

Let's see what the results for the call are.

**Comment by Zimmi48** [comment]
> putting that under the Coq umbrella has some downsides, in particular the management of the account may become less agile, etc...

Agreed, that's why I was suggested a CoqLang account, but still community-managed.

**Comment by ejgallego** [comment]
We will create a twitter account indeed; will close this issue when the account goes live.

**Comment by palmskog** [comment]
The account has now gone live: https://twitter.com/CoqLang

Hence, I'm closing this issue.
