### ISSUE TITLE
Proposal to move Almost Full to coq-community

### ISSUE THREAD

**Issue by palmskog** [coq-community/manifesto#97]
**Project name:** Almost Full

**Initial author(s):** Dimitrios Vytiniotis, Thierry Coquand, and David Wahlstedt

**Current URL:** https://github.com/palmskog/almost-full (tested on Coq 8.11 - 8.12)

**Kind:** pure Coq library & formalization of a mathematical theorem

**License:** MIT License

**Description:** Coq development of almost-full relations, including the Ramsey Theorem, useful for proving termination. As per [this comment](https://xenaproject.wordpress.com/2020/02/09/where-is-the-fashionable-mathematics/#comment-967) the theorem might be used to obtain a constructive version of Hilbert's basis theorem (a challenge posed in [this blog post](https://xenaproject.wordpress.com/2020/02/09/where-is-the-fashionable-mathematics/)).

There is also an [Agda translation](https://github.com/sergei-romanenko/agda-almost-full) from 2014.

**Status:** Unmaintained since 2012

**New maintainer:** @palmskog

**Comment by DmxLarchey** [comment]
Happy to find someone interested in _Almost Full relations_ à la Coquand

Well I do have a constructive library for almost full relations which includes Ramsey's theorem etc up to Kruskal tree theorem and it can be found in here

https://members.loria.fr/DLarchey/files/Kruskal/index.html

But even version `2.0` here is not up to date with recent versions of Coq. However if needed, I could trying to clean my development repo. and publish a version which is up to date with Coq `8.11`.

If you just want Ramsey/Dickson, you could have a look here

https://github.com/DmxLarchey/Ramsey

**Comment by palmskog** [comment]
@DmxLarchey thanks for flagging up those developments!

The main purpose of creating this issue was to show that we do have a pipeline for creating and extending existing Coq projects with interesting properties. As such, if someone takes of the Hibert basis theorem challenge in Coq from Buzzard, that person can now make an informed choice of starting point.

However, since BitBucket is closing down all Mercurial repositories in a few months, have you considered moving the Kruskal development to GitHub and possibly coq-community? We do welcome creator-maintained repositories that could be of interest to others further on, and I can at least contribute continuous integration and metadata boilerplate. (However, it would need to work with 8.11 to join coq-community.)

**Comment by DmxLarchey** [comment]
Well I did convert the BitBucket repo. from `hg` to `git` and it now lives on GitLab (INRIA). May be I could mirror it on GitHub.

Maybe I was a bit fast about the relation between Dickson's lemma and Hilbert's basis theorem though. The reference I was thinking about is _Decision procedure of some relevant logics: a constructive perspective_ by Jacques Riche (JANCL, 14(4), 2004).

**Comment by DmxLarchey** [comment]
May be this one can also help

https://www.andrew.cmu.edu/user/avigad/Students/hertz.pdf

**Comment by Blaisorblade** [comment]
Unrelated, but thanks for resurrecting that code! We read the paper recently, and without that code it was pretty incomplete.

**Comment by palmskog** [comment]
The Almost-Full Coq repo is now updated and works with Coq 8.11 - 8.12 (and `master`). It's also worth noting that there is a constructive Coq proof of Dickson's lemma (used in the last paper linked by Dominique) in the coq-community [Buchberger](https://github.com/coq-community/buchberger) project.

**Comment by palmskog** [comment]
Due to the interest in the library, I reached out to the author @dimitriv who graciously agreed to license it under the MIT license for the benefit of the community.

To have an authoritative location of the library going forward, I will move my repository to coq-community and be the initial maintainer.

**Comment by palmskog** [comment]
The repository has now been moved to: https://github.com/coq-community/almost-full

Hence, I'm closing this issue.
