### ISSUE TITLE
Proposal to move project coqoban to coq-community

### ISSUE THREAD

**Issue by erikmd** [coq-community/manifesto#99]
**Project name:** coqoban (Sokoban in Coq) 

**Initial author(s):** Jasper Stein

**Current URL:** https://github.com/coq-contribs/coqoban

**Kind:** pure Coq library

**License:** LGPL 2.1 (according to the opam package, and I assume it is the same license as Coq, LGPL-2.1-only)

**Description:** A Coq implementation of Sokoban, the Japanese warehouse keepers' game.

**Status:** currently maintained within coq-contribs, cf. https://github.com/coq-contribs/coqoban/issues/1#issuecomment-596749285

**New maintainer:** @erikmd

I'm interested in the maintenance of this library (and more specifically as I explained in https://github.com/coq-contribs/coqoban/issues/1, it'd be great to have soon a release of coqoban for Coq 8.11): coqoban can be viewed at the same time as a formalization pearl − involving dedicated `Notation`s to represent boards as a Coq `Goal` −, and a metaphor − for doing an interactive proof vs. solving a 1-player extensive-form game − that might be used in a pedagogical context.

**Comment by spitters** [comment]
@erikmd Here's some code in case you are interested in making a hi-res version.
We've used it to make hi-res plots of curves in the plane.
https://github.com/coq-community/corn/tree/master/dump

**Comment by erikmd** [comment]
for the time being the plan is essentially to do a Coq 8.11 release, but thanks for your suggestion @spitters ! I'll have a look.

**Comment by Zimmi48** [comment]
@erikmd I've transferred the repository and made you an admin. The README would deserve an update (ideally generated from the standard template) but there's no rush and could happen after the 8.11 release.

**Comment by erikmd** [comment]
OK thanks @Zimmi48, I'm going to update the README and CI

**Comment by erikmd** [comment]
so I opened this PR: https://github.com/coq-community/coqoban/pull/2 ; should we close that issue #99 now?
